name: Build & Test Windows

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

## Build ##

jobs:
  windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create build folder
      run: |
        cd ${{ github.workspace }}
        mkdir build

    - name: Setup build directory cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/build
        key: build-windows-cache-${{ github.ref }}

    - name: Build DPsim
      run: |
        cd ${{ github.workspace }}
        cd build
        git describe --tags --abbrev=0 --match "v*"
        cmake -DWITH_PYBIND=ON ..
        cmake --build . --target dpsim --parallel

    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: build-windows-examples-cache-${{ github.sha }}
        path: ${{ github.workspace }}/build

    - name: Install Python test dependencies
      run: pip install pytest pytest-cov

    - name: Run pytest on notebooks
      run: pytest --cov --cov-branch --cov-report=xml examples/Notebooks/Circuits/

    - name: Upload coverage report
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: AnasBahr/dpsim1
