on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - id: build
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        git describe --tags --abbrev=0 --match "v*"
        cmake -DWITH_PYTHON=OFF ..
        cmake --build .