name: Run a villas example using multiple containers

on:
  workflow_call:
    inputs:
      dpsim_cmd:
        description: 'Command to be run in the dpsim container'
        required: false
        type: string
      compose_file_path:
        # The compose file MUST always include a container named "dpsim" and CAN include a container named "external"
        description: 'Path to the multi-container compose file'
        required: true
        type: string
      external_cmd:
        description: 'Action command to be run in the external container'
        required: false
        type: string
      watcher_cmd:
        description: 'Watcher command to be run in the external container'
        required: false
        type: string

jobs:
  run-villas-example:
    name: Run a villas example across multiple containers
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Restore build archive
      uses: actions/download-artifact@v3
      with:
       name: build-cache
       path: ${{ github.workspace }}/build

    - name: Start containers
      run: cd ${{ inputs.compose_file_path }} && docker-compose -p dpsim-compose up -d

    - name: Configure cmake in dpsim container
      run: docker exec dpsim-compose_dpsim_1 /bin/bash -c "cd /dpsim/build && cmake -DCIM_VERSION=CGMES_2.4.15_16FEB2016 .."

    - name: Build dpsimpyvillas in dpsim container
      run: docker exec dpsim-compose_dpsim_1 /bin/bash -c "cd /dpsim && cmake --build dpsimpyvillas"
    
    - name: Run external container watcher command
      if: ${{ inputs.watcher_cmd }}
      run: docker exec dpsim-compose_external_1 ${{ inputs.watcher_cmd }}&

    - name: Run external container action command
      if: ${{ inputs.external_cmd }}
      run: docker exec dpsim-compose_external_1 ${{ inputs.external_cmd }}&
    
    - name: Run dpsim container command
      if: ${{ inputs.dpsim_cmd }}
      timeout-minutes: 5
      run: docker exec dpsim-compose_dpsim_1 ${{ inputs.dpsim_cmd }}
    